/**
 * Notifications — Area A5 / EP-05 (OWNED, UI surfacing). Must-level:
 *  - FR-5.1 assignment confirmations surfaced  - FR-5.2 reminders surfaced
 * shown as a single feed. Sending is backend-driven; we read and display.
 *
 * Should/Could (FR-5.3 change notices, FR-5.5 preferences, FR-5.6 retry) are
 * OUT of this pass. Assigning a volunteer (Scheduling) produces a confirmation
 * here, demonstrating the FR-5.1 flow end-to-end. Unstyled — design owned elsewhere.
 */
import { useQuery } from '@tanstack/react-query';
import { listNotifications } from '../api/notifications';
import { Async, DataTable, StatusBadge } from '../ui';
import type { NotificationStatus } from '../api/domain';

function tone(status: NotificationStatus): string {
  if (status === 'SENT') return 'success';
  if (status === 'FAILED') return 'error';
  return 'warn';
}

export default function NotificationsPage() {
  const notificationsQuery = useQuery({ queryKey: ['notifications'], queryFn: listNotifications });

  return (
    <main>
      <h1>Notifications</h1>
      <p>Confirmations and reminders generated by the system. Assigning a volunteer adds a confirmation here.</p>
      <Async query={notificationsQuery} empty="No notifications yet.">
        {(rows) => (
          <DataTable
            columns={[
              { header: 'Recipient', cell: (n) => n.recipientName },
              { header: 'Type', cell: (n) => n.type },
              { header: 'Message', cell: (n) => n.message },
              { header: 'When', cell: (n) => new Date(n.timestamp).toLocaleString() },
              { header: 'Status', cell: (n) => <StatusBadge label={n.status} tone={tone(n.status)} /> },
            ]}
            rows={rows}
            getRowKey={(n) => n.id}
            caption="Notification feed"
          />
        )}
      </Async>
    </main>
  );
}
